### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by CVarisco** [SaraVieira/bake-component#2]
Hi @SaraVieira !

first of all, thank you for your contribution to the community 😀 and sorry If I'm writing here.
I follow you for a long time ago and today I see your new project, that's really cool!
Based on that I just thought that maybe we can collaborate on the same goal 😃

Sometimes ago I published something very similar to your project, https://github.com/CVarisco/create-component-app.
But I'll be honest with you, working alone on that project in the last period was not funny anymore,  because everyone has different request without helping me to realize those. 

For me will be a good opportunity to learn something new from you and if you think that can be a good idea, I'll be very happy to collaborate with you to make something great together.
I started working on a [v2](https://github.com/CVarisco/create-component-app/tree/v2.0.0) a long time ago and it could be a good starting point.

Otherwise, no problem at all 😉

Thank you so much for your contribution and keep on like that 💪🏻
Have a nice day,
Christian

**Comment by SaraVieira** [comment]
Heey!

This is so good!

Anything in particular you need help in? Because I would love to help

Same goal and yours is in a waay better state :)

**Comment by SaraVieira** [comment]
I can try to start with this: https://github.com/CVarisco/create-component-app/issues/76

DM me on twitter so it's easier for me to not loose the convo pls: https://mobile.twitter.com/NikkitaFTW

**Comment by CVarisco** [comment]
Cool!
Sure, I'll text to you on Twitter ASAP to help you to understand the state of the project 😃
Thank you so much 😄

**Comment by SaraVieira** [comment]
Dope!!! I shall close this!
